### PR TITLE
Power Perceiver Refactor

### LINKED ISSUE #183: Move experiment 27 in production folder
Move code from experiment 27 into 'production' folder. 
This will allow us to refactor the sub-components while still allowing experiments for R&D to take place.

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

Refactor PP model into own folder and files. Add HuggingFace Hub support

Fixes #183 

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by peterdudfield — COMMENTED** [review]
Hey Jacob, 

Would you be able to add a text to just check the model initialises?
Im sure we could write lots more, but I think at least that first one would be handy

**Comment by jacobbieker** [comment]
> Hey Jacob,
> 
> Would you be able to add a text to just check the model initialises? Im sure we could write lots more, but I think at least that first one would be handy

Yeah, definetely!

**Comment by jacobbieker** [comment]
@peterdudfield the last error seems to be the same as you were seeing in loading the weights, how did you get around it?

**Review by peterdudfield — APPROVED** [review]
Looks great, 
one small lint isort change

**Pull request merged**
